---
- hosts: dev
  become: yes

  tasks:
    - name: Install Apache server
      apt:
        name: apache2
        state: present
      notify: Host static webpage

  handlers:
    - name: Host static webpage
      script: hello.sh
